### ISSUE TITLE
Request flooding bypasses rate limit to some extend

### ISSUE THREAD

**Issue by zhorakaroy** [kkoomen/nestjs-throttler-storage-redis#1064]
The service doesn't work properly when there are for example more than 5 requests in a second, for example, the limitation is 5 requests per second.

if we did the requests by Postman or Browser all will work fine.

But if we use the script to make requests for example 1000 per second, the guard will not work and will forward a request to the controller.   @Throttle(5, 1)

I changed storage from Redis to memory and it works fine for 1000 requests for a second, and after 5 requests the guard is activating.

As I understand the logic written in functions addRecord and getRecord works very slowly, for that it's working when we make requests by the postman and doesn't work when we use the script for checking.

**Comment by kkoomen** [comment]
Which version of nestjs-throttler-storage-redis are you currently using? This should not be a problem with the latest 0.2.2 version.

**Comment by zhorakaroy** [comment]
the version is 0.2.2.

The issue is related to Redis storage. because without RedisStorage(in memory) the guard is working perfectly.

I think the logic written in addRecord and getRecord works very slowly, for it can't accumulate requests. @kkoomen

**Comment by zhorakaroy** [comment]
This is the script which I use for testing.

`
const axios = require('axios');

for (let i = 0; i < 1000; i++) {
  axios
    .get('http://localhost:9000/v1/test')
    .then(({ data }) => console.count())
    .catch((err) => {
      console.log(err.toString());
    });
}
`

**Comment by kkoomen** [comment]
This has been released in version v0.3.0 on [NPM](https://www.npmjs.com/package/nestjs-throttler-storage-redis). Special thanks to @zhorakaroy for discovering this nasty bug. This was a good improvement for the nestjs throttler core package as well as for this package.
