### ISSUE TITLE
WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by Igorsharf** [kkoomen/nestjs-throttler-storage-redis#1096]
Hey, just upgraded to version 4.0.0 two days ago, and since then getting sometimes this error:

ERR Error running script (call to f_f7788d43191d9ad66c866e8c63f3c3e361391849): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value
stack:ReplyError: ERR Error running script (call to f_f7788d43191d9ad66c866e8c63f3c3e361391849): @user_script:1: WRONGTYPE Operation against a key holding the wrong kind of value
at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
name:ReplyError
type:ReplyError
}

Happens on the increment operation...Has anyone encountered this??

**Comment by kkoomen** [comment]
@Igorsharf Have you updated the package and then continued to use the package on the same database? because that might run into problems. Clear the redis database and try again. The newer v4.0.0 version has a big structural change that might require a fresh database to start with.

**Comment by Tzvika-m** [comment]
Thanks @kkoomen, is there a way to identify the package's keys and clear them specifically?

**Comment by Igorsharf** [comment]
@kkoomen still same error after deleting all keys...
A lot of errors during a scope of few minutes and then works fine again for some time...

Any other solutions?

**Comment by kkoomen** [comment]
@Tzvika-m you can flush all keys, but if you can't afford to do that then you can look for MD5 hashes of length 32, here's an example hash: `7d8e43bbc8dc2c3a94c3e79df0a590d6`.

You can also use `redis-cli monitor` to see the hashes when requests are being made.

---

@Igorsharf Please provide a demo repo that can reproduce the error and then I'll have a look at it.

**Comment by Igorsharf** [comment]
@kkoomen Yes I understand the change, just not way it causes this error that required me to delete all keys from redis...

**Comment by kkoomen** [comment]
@Igorsharf because prior to the breaking changes a key would return an int, being the `ttl` value, but now it returns an array of two integers being `[totalHits, timeToExpire]`, so existing keys will throw an error about the type being returned, as it does not abide by the new format.
