### ISSUE TITLE
Wrong `timeToExpire` unit

### ISSUE THREAD

**Issue by AntunVukicevic** [kkoomen/nestjs-throttler-storage-redis#1167]
`timeToExpire` value returned from the `increment` function is in milliseconds instead of seconds. Because of that NestJs `ThrottlerGuard` sets the wrong `Retry-After` header in the HTTP response when the throttling limit is hit.

From the quick debug session, it looks like calling the [PTTL](https://redis.io/commands/pttl/) Redis command returns milliseconds that are not converted to seconds afterwards.

**Comment by slavafomin** [comment]
I can confirm this issue. The content of the `Retry-After` header is incorrect. It should contain seconds, while in practice in contains milliseconds. I think we should convert millis to seconds [here](https://github.com/kkoomen/nestjs-throttler-storage-redis/blob/master/src/throttler-storage-redis.service.ts#L73) right before we return the result to the guard.

**Comment by kkoomen** [comment]
Hi. Thanks a lot for noticing this, unfortunately this became a problem during the big rewrite last time. The tests did check for a number, but not a specific number. I've modified tests to make sure the secs are beings checked to make sure this won't happen again in the future.

I've just released this immediately under v0.3.1 on NPM.

**Comment by kkoomen** [comment]
Hi. Thanks a lot for noticing this, unfortunately this became a problem during the big rewrite last time. The tests did check for a number, but not a specific number. I've modified tests to make sure the secs are beings checked to make sure this won't happen again in the future.

I've just released this immediately under v0.3.2 on NPM.
