### ISSUE TITLE
reflect-metadata ^0.2.1

### ISSUE THREAD

**Issue by garins83** [kkoomen/nestjs-throttler-storage-redis#1610]
Please make the version up

**Comment by kkoomen** [comment]
0.4.2 is published on NPM with this fix.

**Comment by HarrySky** [comment]
@kkoomen it seems that `"reflect-metadata": "^0.1.13"` is still present in peer dependencies

**Comment by kkoomen** [comment]
@HarrySky Good catch, I accidently only updated the dev dep. I just released v0.4.3 on NPM.
