### ISSUE TITLE
if pass redis options will raise error

### ISSUE THREAD

**Issue by Diluka** [kkoomen/nestjs-throttler-storage-redis#233]
```ts
  imports: [
    ThrottlerModule.forRootAsync({
      inject: [ConfigService],
      useFactory: (config) => ({ storage: new ThrottlerStorageRedisService(config.get('redis[1]')) }), // if pass options
    }),
  ],
```

```ts
{host:'127.0.0.1',port:6379,name:'1',db:1}
```

`UnhandledPromiseRejectionWarning: ReplyError: ERR value is not an integer or out of range`

# version
- npm ioredis `^4.19.4`
- server redis `6`

# update
always throw error if requested endpoint is protected

**Comment by Diluka** [comment]
still in latest version using `@nestjs/throttler`

**Comment by kkoomen** [comment]
The `ReplyError` is an indicator that your input is not always correct. This is a redis issue that you have yourself and is not related to this plugin nor `@nestjs/throttler`. We just pass the options directly to `ioredis`, this is just a simple wrapper package.
