### ISSUE TITLE
How to ensure the atomic operation of Redis

### ISSUE THREAD

**Issue by perpyy** [kkoomen/nestjs-throttler-storage-redis#351]
How does Redis get set guarantee atomicity in the cluster environment of PM2 with multiple processes

**Comment by kkoomen** [comment]
I don't know if this is a joke, but this is off-topic.

**Comment by perpyy** [comment]
this is not a joke.

[https://github.com/nestjs/throttler/blob/master/src/throttler.guard.ts](https://github.com/nestjs/throttler/blob/master/src/throttler.guard.ts)

in method `handleRequest`,  between `getRecord` and `addRecord`.
In the distributed case, don't you think there will be another get / add  Record between these two calls ?

**Comment by kkoomen** [comment]
If you'd made your initial description like this, then I would not close it.

To answer you question, no I am 99% sure there will be no problem with this. There are no other async operations being done that need to be `await`ed so this process is being handled very rapidly. The current behavior works for many people, although it hasn't been tested on a cluster environment by the people who've worked on the project.

If you experience a problem with it, feel free to submit another issue.
