### ISSUE TITLE
Problems with Redis storage

### ISSUE THREAD

**Issue by RomanSavka-Sir** [kkoomen/nestjs-throttler-storage-redis#642]
I have one issue that can understand:
When I use ThrottlerStorageRedisService into ThrottlerModule.forRoot and pass redis as prameter Redis don't keeps track of the requests.
I wanna see all request information into Redis memory but its empty.
Maybe I should use getRecord and  addRecord methods from  ThrottlerStorageRedisService directly into my endpoints?

**Comment by kkoomen** [comment]
>  I wanna see all request information into Redis memory but its empty.

This plugin only sets TTL keys for the nestjs throttler. Redis 'requests' isn't part of this plugin.
