### ISSUE TITLE
`Maximum call stack size exceeded` error while e2e test my NestJS app

### ISSUE THREAD

**Issue by kasir-barati** [kkoomen/nestjs-throttler-storage-redis#750]
Thanks for this awesome module that make my life easier

# The initial question:
> Is it normal to face `Maximum call stack size exceeded` error while running e2e test on  `AppModule`?

# Description:
My NestJS application runs in the prod mode and dev mode. But I cannot execute an e2e test on the `AppModule`. Basically I have too many 3rd party packages and it happens while importing `ThrottlerStorageRedisService` and other 3rd party modules are OK.

# My assumption:
I am not sure it was something related to Jest or NestJS. Just my guess something between your package and `ioredis` is wrong. As you see in the screenshot the call stack error happened in that module.

## Why I guess like that?
I test this solution too, I import it as the last module, All other modules imported correctly but this module cause `Maximum call stack size exceeded` error.

# Expected behavior

My e2e runs and I could write my e2e tests.

# What happened: 
This error that you see occurred.
![Screenshot from it](https://user-images.githubusercontent.com/73785723/160068251-8b8ba58f-3248-46d0-ac29-d88c3d6dd19d.png)

Node version: 17.6.0
And here is my devDep and dep copied from `package.json`:
```json
"scripts": {
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:e2e": "NODE_ENV=test jest --config ./test/e2e.config.ts --watch",
},
"dependencies": {
    "@nestjs-modules/mailer": "^1.6.1",
    "@nestjs/bull": "^0.5.0",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^1.1.6",
    "@nestjs/core": "^8.0.0",
    "@nestjs/event-emitter": "^1.0.0",
    "@nestjs/jwt": "^8.0.0",
    "@nestjs/passport": "^8.0.1",
    "@nestjs/platform-express": "^8.0.0",
    "@nestjs/schedule": "^1.0.2",
    "@nestjs/swagger": "^5.1.4",
    "@nestjs/throttler": "^2.0.0",
    "buffer": "^6.0.3",
    "bull": "^4.6.2",
    "cache-manager": "^3.6.0",
    "cache-manager-redis-store": "^2.0.0",
    "env-cmd": "^10.1.0",
    "ioredis": "^4.28.5",
    "nestjs-throttler-storage-redis": "^0.1.18",
    "reflect-metadata": "^0.1.13",
},
"devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/bcrypt": "^5.0.0",
    "@types/bcryptjs": "^2.4.2",
    "@types/bull": "^3.15.8",
    "@types/cache-manager": "^3.4.2",
    "@types/cron": "^1.7.3",
    "@types/express": "^4.17.13",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.0.0",
    "@types/passport-jwt": "^3.0.6",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^4.28.2",
    "@typescript-eslint/parser": "^4.28.2",
    "eslint": "^7.30.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "^27.0.6",
    "prettier": "^2.3.2",
    "prisma": "^3.3.0",
    "prisma-dbml-generator": "^0.8.3",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
},
```

Do you have any Idea what is wrong?

**Comment by kkoomen** [comment]
Can you upgrade to v0.2.0 or higher and test this issue again? Otherwise I'll close this issue.

**Comment by mehdibo** [comment]
@kkoomen

There was this line: `this.disconnectRequired = true;` in `throttler-storage-redis.service.ts` but that's no longer the case.
This line was introduced a year ago: https://github.com/kkoomen/nestjs-throttler-storage-redis/commit/52470fac523c6ad84f3de79e4dac4905f41b8009

**Comment by kkoomen** [comment]
@mehdibo alright, then I'll close this.
